language: node_js
sudo: false
node_js:
- '4.2'
before_install:
- cp ci/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
- $HOME/travis-ci.sh before-install
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
- $HOME/travis-ci.sh before-deploy
after_deploy:
- $HOME/travis-ci.sh after-deploy
cache:
  directories:
  - node_modules
notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalabox.io
    - riley@kalabox.io
    on_success: always
deploy:
  provider: npm
  email: mike@kalamuna.com
  api_key:
    secure: QlBk3ArzdGYj2K8gekbAbqRdXgFWnJfugQIBypB1kBFMFUoEaS5Hp9/wujeA4ABxNKL/o2UpJn8UjG3dR/ZmugmcUb/maeIwTA8VeMxcjdHdB6ijtVPObNrouH5Rz0RcHbsPvyoKbFJFawpt90ivFERyLba9cD9HVPPZbYsFhCQ=
  on:
    tags: true
    repo: kalabox/kalabox-app-php
    branch: v0.12
