#
# Kalabox Pantheon compose file
#
# This contains the core service definitions for Pantheon-on-Kalabox. This
# is a docker-compose file so please check out the compose file documentation
# over at https://docs.docker.com/compose/compose-file/.
#
# There are, however, a few caveats to take into account kalabox-compose.ymls
#
#   1. It is probably a bad idea to use the `container_name` key.
#
#   2. You can run `kbox env` inside of your app for a list of environmental
#      variables that you can use inside of this compose file.
#
#   3. Ports need to be exposed to the host on the outside using
#
#      ports:
#       - "PORTNUMBER"
#
#      Otherwise they are not usable in the services plugin.
#
#    4. The config directory in your app root contains a lot of
#       service config that is shared into each service. This is all
#       editable directly and should take on a `kbox restart`.
#

#
# This defines a data container to share common Pantheon app assets such as:
#
#   1. /media - Static assets like images and compiled css, Your files/wp-uploads
#               directory is symlinked here
#
#   2. /certs - Shared service certs
#
#   3. /sql - MariaDB databases to preserve data on rebuilds
#
#   4. /code - Your applications codebase, also where you shared code lives
#
#   5. /backups - Backups that are downloaded from Pantheon
#
data:
  image: busybox
  volumes:
    - $KALABOX_APP_ROOT_BIND/files:/media:rw
    - /var/lib/mysql
    - /var/www/html
  command: chown 33:33 -Rv /var/www/html

#
# This defines a Pantheon appserver.
#
# We are currently running the same services as the Pantheon appserver with
# the current exception of apache tika.
#
# We also populate this service with similar environmental variables to what
# you would find on the pantheon appserver so you can make use of things
# like:
#
#   PRESSFLOW_SETTINGS
#   PANTHEON_ENVIRONMENT
#   CACHE_HOST
#
# Check your services config in kalabox.yml on how to access this directly
# instead of going through the edge service.
#
appserver:
  image: drupal:$KALABOX_APP_DRUPAL_CONFIG_VERSION
  volumes_from:
    - data
  links:
    - db:database
  ports:
    - "80"

#
# This defines a Pantheon database server.
#
db:
  image: mysql
  volumes_from:
    - data
  ports:
    - "3306"
  environment:
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_ROOT_PASSWORD: drupal
    MYSQL_DATABASE: drupal
